/*
 * Copyright (C) 2013-2015 terasoluna.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.terasoluna.gfw.common.fullhalf;

public class DefaultFullHalf {

	public static final FullHalfConverter INSTANCE = new FullHalfConverter(
			new FullHalfPairsBuilder()
                .pair("！", "!")
                .pair("”", "\"")
                .pair("＃", "#")
                .pair("＄", "$")
                .pair("％", "%")
                .pair("＆", "&")
                .pair("’", "'")
                .pair("（", "(")
                .pair("）", ")")
                .pair("＊", "*")
                .pair("＋", "+")
                .pair("，", ",")
                .pair("－", "-")
                .pair("．", ".")
                .pair("／", "/")
                .pair("０", "0")
                .pair("１", "1")
                .pair("２", "2")
                .pair("３", "3")
                .pair("４", "4")
                .pair("５", "5")
                .pair("６", "6")
                .pair("７", "7")
                .pair("８", "8")
                .pair("９", "9")
                .pair("：", ":")
                .pair("；", ";")
                .pair("＜", "<")
                .pair("＝", "=")
                .pair("＞", ">")
                .pair("？", "?")
                .pair("＠", "@")
                .pair("Ａ", "A")
                .pair("Ｂ", "B")
                .pair("Ｃ", "C")
                .pair("Ｄ", "D")
                .pair("Ｅ", "E")
                .pair("Ｆ", "F")
                .pair("Ｇ", "G")
                .pair("Ｈ", "H")
                .pair("Ｉ", "I")
                .pair("Ｊ", "J")
                .pair("Ｋ", "K")
                .pair("Ｌ", "L")
                .pair("Ｍ", "M")
                .pair("Ｎ", "N")
                .pair("Ｏ", "O")
                .pair("Ｐ", "P")
                .pair("Ｑ", "Q")
                .pair("Ｒ", "R")
                .pair("Ｓ", "S")
                .pair("Ｔ", "T")
                .pair("Ｕ", "U")
                .pair("Ｖ", "V")
                .pair("Ｗ", "W")
                .pair("Ｘ", "X")
                .pair("Ｙ", "Y")
                .pair("Ｚ", "Z")
                .pair("［", "[")
                .pair("￥", "\\")
                .pair("］", "]")
                .pair("＾", "^")
                .pair("＿", "_")
                .pair("｀", "`")
                .pair("ａ", "a")
                .pair("ｂ", "b")
                .pair("ｃ", "c")
                .pair("ｄ", "d")
                .pair("ｅ", "e")
                .pair("ｆ", "f")
                .pair("ｇ", "g")
                .pair("ｈ", "h")
                .pair("ｉ", "i")
                .pair("ｊ", "j")
                .pair("ｋ", "k")
                .pair("ｌ", "l")
                .pair("ｍ", "m")
                .pair("ｎ", "n")
                .pair("ｏ", "o")
                .pair("ｐ", "p")
                .pair("ｑ", "q")
                .pair("ｒ", "r")
                .pair("ｓ", "s")
                .pair("ｔ", "t")
                .pair("ｕ", "u")
                .pair("ｖ", "v")
                .pair("ｗ", "w")
                .pair("ｘ", "x")
                .pair("ｙ", "y")
                .pair("ｚ", "z")
                .pair("｛", "{")
                .pair("｜", "|")
                .pair("｝", "}")
                .pair("\uff5e", "~")
                .pair("。", "｡")
                .pair("「", "｢")
                .pair("」", "｣")
                .pair("、", "､")
                .pair("・", "･")
                .pair("ァ", "ｧ")
                .pair("ィ", "ｨ")
                .pair("ゥ", "ｩ")
                .pair("ェ", "ｪ")
                .pair("ォ", "ｫ")
                .pair("ャ", "ｬ")
                .pair("ュ", "ｭ")
                .pair("ョ", "ｮ")
                .pair("ッ", "ｯ")
                .pair("ー", "ｰ")
                .pair("ア", "ｱ")
                .pair("イ", "ｲ")
                .pair("ウ", "ｳ")
                .pair("エ", "ｴ")
                .pair("オ", "ｵ")
                .pair("カ", "ｶ")
                .pair("キ", "ｷ")
                .pair("ク", "ｸ")
                .pair("ケ", "ｹ")
                .pair("コ", "ｺ")
                .pair("サ", "ｻ")
                .pair("シ", "ｼ")
                .pair("ス", "ｽ")
                .pair("セ", "ｾ")
                .pair("ソ", "ｿ")
                .pair("タ", "ﾀ")
                .pair("チ", "ﾁ")
                .pair("ツ", "ﾂ")
                .pair("テ", "ﾃ")
                .pair("ト", "ﾄ")
                .pair("ナ", "ﾅ")
                .pair("ニ", "ﾆ")
                .pair("ヌ", "ﾇ")
                .pair("ネ", "ﾈ")
                .pair("ノ", "ﾉ")
                .pair("ハ", "ﾊ")
                .pair("ヒ", "ﾋ")
                .pair("フ", "ﾌ")
                .pair("ヘ", "ﾍ")
                .pair("ホ", "ﾎ")
                .pair("マ", "ﾏ")
                .pair("ミ", "ﾐ")
                .pair("ム", "ﾑ")
                .pair("メ", "ﾒ")
                .pair("モ", "ﾓ")
                .pair("ヤ", "ﾔ")
                .pair("ユ", "ﾕ")
                .pair("ヨ", "ﾖ")
                .pair("ラ", "ﾗ")
                .pair("リ", "ﾘ")
                .pair("ル", "ﾙ")
                .pair("レ", "ﾚ")
                .pair("ロ", "ﾛ")
                .pair("ワ", "ﾜ")
                .pair("ヲ", "ｦ")
                .pair("ン", "ﾝ")
                .pair("ガ", "ｶﾞ")
                .pair("ギ", "ｷﾞ")
                .pair("グ", "ｸﾞ")
                .pair("ゲ", "ｹﾞ")
                .pair("ゴ", "ｺﾞ")
                .pair("ザ", "ｻﾞ")
                .pair("ジ", "ｼﾞ")
                .pair("ズ", "ｽﾞ")
                .pair("ゼ", "ｾﾞ")
                .pair("ゾ", "ｿﾞ")
                .pair("ダ", "ﾀﾞ")
                .pair("ヂ", "ﾁﾞ")
                .pair("ヅ", "ﾂﾞ")
                .pair("デ", "ﾃﾞ")
                .pair("ド", "ﾄﾞ")
                .pair("バ", "ﾊﾞ")
                .pair("ビ", "ﾋﾞ")
                .pair("ブ", "ﾌﾞ")
                .pair("べ", "ﾍﾞ")
                .pair("ボ", "ﾎﾞ")
                .pair("パ", "ﾊﾟ")
                .pair("ピ", "ﾋﾟ")
                .pair("プ", "ﾌﾟ")
                .pair("ペ", "ﾍﾟ")
                .pair("ポ", "ﾎﾟ")
                .pair("ヴ", "ｳﾞ")
                .pair("\u30f7", "ﾜﾞ")
                .pair("\u30fa", "ｦﾞ")
                .pair("゛", "ﾞ")
                .pair("゜", "ﾟ")
                .pair("　", " ")
                .build());
}
